### ISSUE TITLE
Release Candidate Checklist

### ISSUE THREAD

**Issue by tolmasky** [runkitdev/isomorphic#2]
- [ ] Uglify each file (wrap twice: once for module function, once for global -- or find a way to minify global away)
- [ ] Proper caching based on yarn/package-lock
- [ ] Resolve babel plugins correctly
   - [ ] Use remove-unnecessary-closures
- [ ] Remove dead code (process.env.NODE_ENV if removal)
- [ ] Pass process.env through
- [ ] Place checksums in the script tag, keep forwarding them
- [ ] Properly account for "main" entry in `package.json`
   - [ ] Properly account for native module dependencies
- [ ] Finalize native module require
- [ ] Support source-maps
- [ ] Finalize / vs. ~
